### ISSUE TITLE
Запуск с tapdance

### ISSUE THREAD

**Issue by Ze2QvoQxxKeu** [dimuls/rkn-bypasser#1]
Каким образом в текущей версии запустить сервис с тапденс?
Команда `rkn-bypasser run -addr 127.0.1.1:8000` вызывает `panic: runtime error: invalid memory address or nil pointer dereference`
Полный лог:
```
C:\Go\bin>rkn-bypasser run -addr 127.0.1.1:8000
2018-04-25 09:06:39.646183 Running at 127.0.1.1:8000 without tor
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x77c190]

goroutine 1 [running]:
github.com/someanon/rkn-bypasser/proxy.loadBlockedIPs(0xc042059728, 0x4e75e1)
        C:/Users/root/go/src/github.com/someanon/rkn-bypasser/proxy/blockedIPs.go:23 +0xa0
github.com/someanon/rkn-bypasser/proxy.initBlockedIPs()
        C:/Users/root/go/src/github.com/someanon/rkn-bypasser/proxy/blockedIPs.go:45 +0x2d
github.com/someanon/rkn-bypasser/proxy.Run(0xc042008100, 0xe, 0x0, 0x0)
        C:/Users/root/go/src/github.com/someanon/rkn-bypasser/proxy/proxy.go:43 +0x3b
main.run(0xc04206cc60, 0x0, 0xc04206cc60)
        C:/Users/root/go/src/github.com/someanon/rkn-bypasser/run.go:32 +0x21d
gopkg.in/urfave/cli%2ev1.HandleAction(0x7d6dc0, 0x873a70, 0xc04206cc60, 0xc042034300, 0x0)
        C:/Users/root/go/src/gopkg.in/urfave/cli.v1/app.go:490 +0xd9
gopkg.in/urfave/cli%2ev1.Command.Run(0x85a187, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x85dfcd, 0x10, 0x0, ...)
        C:/Users/root/go/src/gopkg.in/urfave/cli.v1/command.go:210 +0xa9c
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc042042820, 0xc0420320c0, 0x4, 0x4, 0x0, 0x0)
        C:/Users/root/go/src/gopkg.in/urfave/cli.v1/app.go:255 +0x6ff
main.main()
        C:/Users/root/go/src/github.com/someanon/rkn-bypasser/main.go:98 +0x8b3
```

**Comment by someanon** [comment]
Попробуй ещё раз собрать последнюю версию из мастера. Судя по стектрейсу это ошибки уже не должно быть.

**Comment by dimuls** [comment]
Я вернул поддержку tapdance, после последних изменений в оригинальном репе он заработал.
